#129841 DSK:(EDUSUB)AFDCLN.SUB Abort-Notice (3) 

; Processed:  Req #129841 DSK:(EDUSUB)AFDCLN.TMP=DSK:(EDUSUB)AFDCLN.SUB
; Scheduled:  02-Feb-92 07:00:00
; Actual run: 02-Feb-92 07:00:00
;
; Options:  Log:Supersede Mail:Error Restart:Repeat Unique:Job
; Limits:  Time 100  TRUs 0
; Flags: 
; Status:  Abort-Notice (3)  at  02-Feb-92 12:32:16
;
; Output recorded in file DSK:(EDUSUB)AFDCLN.TMP.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Sun, 5 Apr 92 12:22:47 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
Invalid address(s):
<DAUERBACH>


----------
RCPT To: <DAUERBACH> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sun, 5 Apr 92 12:22:46 UT 
To: DAUERBACH 
Subject: Req #130220 DSK:(DAUERBACH)BACKUP.MON Abort-License (0) 

; Processed:  Req #130220 DSK:(DAUERBACH)BACKUP.MON
; Scheduled:  05-Apr-92 08:00:00
; Actual run: 01-Mar-92 08:16:31
;
; Options:  Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  05-Apr-92 08:22:45

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 6 Apr 92 0:00:03 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: 44062410777
Last logout: 1 Jan 64


----------
RCPT To: <DAUERBACH> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 7 Mar 92 1:00:20 UT 
To: DAUERBACH 
Subject: Req #130280 DSK:(DAUERBACH)BACKUP.DAY Abort-License (0) 

; Processed:  Req #130280 DSK:(DAUERBACH)BACKUP.DAY
; Scheduled:  06-Mar-92 20:00:00
; Actual run: 05-Mar-92 20:00:16
;
; Options:  Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  06-Mar-92 20:00:20

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 6 Apr 92 0:00:05 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: 44062410777
Last logout: 1 Jan 64


----------
RCPT To: <DAUERBACH> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 7 Mar 92 13:00:13 UT 
To: DAUERBACH 
Subject: Req #130208 DSK:(DAUERBACH)BACKUP.WK Abort-License (0) 

; Processed:  Req #130208 DSK:(DAUERBACH)BACKUP.WK
; Scheduled:  07-Mar-92 08:00:00
; Actual run: 29-Feb-92 08:00:14
;
; Options:  Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  07-Mar-92 08:00:12

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Fri, 29 May 92 23:16:33 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
Invalid address(s):
<VACODE>


----------
RCPT To: <VACODE> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Fri, 29 May 92 23:16:32 UT 
To: VACODE 
Subject: Req #124943 DSK:(VACODE)LSTAT.SUB Abort-License (0) 

; Processed:  Req #124943 DSK:(VACODE)LSTAT.OUT=DSK:(VACODE)LSTAT.SUB
; Scheduled:  29-May-92 19:07:48
; Actual run: 26-Feb-91 00:29:03
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  29-May-92 19:16:28
;
; Output recorded in file DSK:(VACODE)LSTAT.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 18 Jun 92 0:00:05 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: LWOLF
Last logout: 17 Jun 92


----------
RCPT To: <LWOLF> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Tue, 19 May 92 20:41:13 UT 
To: LWOLF 
Subject: Req #160 DSK:(ENSS)LEN Abort-Input (0) 

; Processed:  Req #160 DSK:(ENSS)LEN.LOG=DSK:(ENSS)LEN
; Scheduled:  19-May-92 16:41:00
; Actual run: 19-May-92 16:41:03
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-Input (0)  at  19-May-92 16:41:12
;
; Output recorded in file DSK:(ENSS)LEN.LOG.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 18 Jun 92 0:00:06 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: LWOLF
Last logout: 17 Jun 92


----------
RCPT To: <LWOLF> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Fri, 29 May 92 23:14:02 UT 
To: LWOLF 
Subject: Req #160 DSK:(ENSS)LEN Abort-Input (0) 

; Processed:  Req #160 DSK:(ENSS)LEN.LOG=DSK:(ENSS)LEN
; Scheduled:  29-May-92 19:07:56
; Actual run: 29-May-92 19:13:55
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-Input (0)  at  29-May-92 19:14:01
;
; Output recorded in file DSK:(ENSS)LEN.LOG.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 29 Jun 92 21:01:18 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: UKL
Last logout: 9 Jun 92


----------
RCPT To: <UKL> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 30 May 92 10:07:40 UT 
To: UKL 
Subject: Req #335 DSK:(BTSUB)AFDCLN.SUB Abort-Notice (4) 

; Processed:  Req #335 DSK:(BTSUB)AFDCLN.TMP=DSK:(BTSUB)AFDCLN.SUB
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 30-May-92 04:00:13
;
; Options:  Log:Supersede Mail:Error Restart:Repeat Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-Notice (4)  at  30-May-92 10:07:40
;
; Output recorded in file DSK:(BTSUB)AFDCLN.TMP.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 20 Jul 92 0:00:02 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: INTSUB
Last logout: 20 Jun 92


----------
RCPT To: <INTSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 20 Jun 92 11:06:52 UT 
To: INTSUB 
Subject: Req #662 DSK:(INTSUB)SOFTVN.CMD Abort-Zap (6) 

; Processed:  Req #662 DSK:(INTSUB)SOFTVN.DOC=DSK:(INTSUB)SOFTVN.CMD
; Scheduled:  20-Jun-92 12:00:00
; Actual run: 20-Jun-92 12:06:17
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 222  TRUs 0
; Flags: 
; Status:  Abort-Zap (6)  at  20-Jun-92 12:06:51
;
; Output recorded in file DSK:(INTSUB)SOFTVN.DOC.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 27 Jul 92 0:00:01 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: KBSUB
Last logout: 20 Jun 92


----------
RCPT To: <KBSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 27 Jun 92 16:33:41 UT 
To: KBSUB 
Subject: Req #838 DSK:(KBSUB)SOFTVN.CMD Abort-Zap (6) 

; Processed:  Req #838 DSK:(KBSUB)SOFTVN.TMP=DSK:(KBSUB)SOFTVN.CMD
; Scheduled:  27-Jun-92 16:15:00
; Actual run: 27-Jun-92 17:33:00
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 120  TRUs 0
; Flags: 
; Status:  Abort-Zap (6)  at  27-Jun-92 17:33:37
;
; Output recorded in file DSK:(KBSUB)SOFTVN.TMP.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:09 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Tue, 30 Jun 92 20:00:04 UT 
To: ENSS 
Subject: Req #1038 DSK:(ENSS)ONTSLV.SUB Abort-License (0) 

; Processed:  Req #1038 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  30-Jun-92 16:00:00
; Actual run: 30-Jun-92 12:00:05
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  30-Jun-92 16:00:01
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:09 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Wed, 1 Jul 92 0:00:08 UT 
To: ENSS 
Subject: Req #1023 DSK:(ENSS)BACKUP.DAY Abort-License (0) 

; Processed:  Req #1023 DSK:(ENSS)BACKUP.DAY
; Scheduled:  30-Jun-92 20:00:00
; Actual run: 29-Jun-92 20:00:12
;
; Options:  Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  30-Jun-92 20:00:06

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:10 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Wed, 1 Jul 92 3:00:07 UT 
To: ENSS 
Subject: Req #1026 DSK:(ENSS)PROOF.SUB Abort-License (0) 

; Processed:  Req #1026 DSK:(ENSS)PROOF.OUT=DSK:(ENSS)PROOF.SUB
; Scheduled:  30-Jun-92 23:00:00
; Actual run: 29-Jun-92 23:00:03
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  30-Jun-92 23:00:05
;
; Output recorded in file DSK:(ENSS)PROOF.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:10 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sun, 5 Jul 92 12:00:05 UT 
To: ENSS 
Subject: Req #518 DSK:(ENSS)BACKUP.MON Abort-License (0) 

; Processed:  Req #518 DSK:(ENSS)BACKUP.MON
; Scheduled:  05-Jul-92 08:00:00
; Actual run: 07-Jun-92 08:52:41
;
; Options:  Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  05-Jul-92 08:00:04

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:10 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Tue, 7 Jul 92 15:38:21 UT 
To: ENSS 
Subject: Req #1026 DSK:(ENSS)PROOF.SUB Abort-License (0) 

; Processed:  Req #1026 DSK:(ENSS)PROOF.OUT=DSK:(ENSS)PROOF.SUB
; Scheduled:  07-Jul-92 11:38:04
; Actual run: 29-Jun-92 23:00:03
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  07-Jul-92 11:38:12
;
; Output recorded in file DSK:(ENSS)PROOF.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:11 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Tue, 7 Jul 92 15:38:37 UT 
To: ENSS 
Subject: Req #1038 DSK:(ENSS)ONTSLV.SUB Abort-License (0) 

; Processed:  Req #1038 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  07-Jul-92 11:38:06
; Actual run: 30-Jun-92 12:00:05
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  07-Jul-92 11:38:32
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:11 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Tue, 7 Jul 92 15:39:12 UT 
To: ENSS 
Subject: Req #518 DSK:(ENSS)BACKUP.MON Abort-License (0) 

; Processed:  Req #518 DSK:(ENSS)BACKUP.MON
; Scheduled:  07-Jul-92 11:38:13
; Actual run: 07-Jun-92 08:52:41
;
; Options:  Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  07-Jul-92 11:39:10

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:11 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Tue, 7 Jul 92 15:39:35 UT 
To: ENSS 
Subject: Req #836 DSK:(ENSS)BACKUP.WK Abort-License (0) 

; Processed:  Req #836 DSK:(ENSS)BACKUP.WK
; Scheduled:  07-Jul-92 11:38:20
; Actual run: 27-Jun-92 12:32:38
;
; Options:  Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  07-Jul-92 11:39:32

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:12 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Tue, 7 Jul 92 15:43:37 UT 
To: ENSS 
Subject: Req #1026 DSK:(ENSS)PROOF.SUB Abort-License (0) 

; Processed:  Req #1026 DSK:(ENSS)PROOF.OUT=DSK:(ENSS)PROOF.SUB
; Scheduled:  07-Jul-92 11:43:19
; Actual run: 29-Jun-92 23:00:03
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  07-Jul-92 11:43:32
;
; Output recorded in file DSK:(ENSS)PROOF.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:12 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Tue, 7 Jul 92 15:43:52 UT 
To: ENSS 
Subject: Req #1038 DSK:(ENSS)ONTSLV.SUB Abort-License (0) 

; Processed:  Req #1038 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  07-Jul-92 11:43:28
; Actual run: 30-Jun-92 12:00:05
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  07-Jul-92 11:43:47
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:13 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Tue, 7 Jul 92 15:44:12 UT 
To: ENSS 
Subject: Req #1023 DSK:(ENSS)BACKUP.DAY Abort-License (0) 

; Processed:  Req #1023 DSK:(ENSS)BACKUP.DAY
; Scheduled:  07-Jul-92 11:43:40
; Actual run: 29-Jun-92 20:00:12
;
; Options:  Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  07-Jul-92 11:44:08

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:14 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 11 Jul 92 12:00:15 UT 
To: ENSS 
Subject: Req #836 DSK:(ENSS)BACKUP.WK Abort-License (0) 

; Processed:  Req #836 DSK:(ENSS)BACKUP.WK
; Scheduled:  11-Jul-92 08:00:00
; Actual run: 27-Jun-92 12:32:38
;
; Options:  Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  11-Jul-92 08:00:14

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:14 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 18 Jul 92 8:20:46 UT 
To: ENSS 
Subject: Req #1357 DSK:(ENSS)ONTSLV.SUB Abort-Enter (3) 

; Processed:  Req #1357 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  17-Jul-92 16:00:00
; Actual run: 18-Jul-92 04:20:39
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Enter (3)  at  18-Jul-92 04:20:45
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:15 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From:Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 18 Jul 92 8:20:55 UT 
To: ENSS 
Subject: Req #1344 DSK:(ENSS)PROOF.SUB Abort-Enter (3) 

; Processed:  Req #1344 DSK:(ENSS)PROOF.OUT=DSK:(ENSS)PROOF.SUB
; Scheduled:  17-Jul-92 23:00:00
; Actual run: 18-Jul-92 04:20:48
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Enter (3)  at  18-Jul-92 04:20:54
;
; Output recorded in file DSK:(ENSS)PROOF.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 30 Jul 92 0:00:16 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 29 Jul 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 25 Jul 92 7:33:41 UT 
To: ENSS 
Subject: Req #1518 DSK:(ENSS)ONTSLV.SUB Abort-Enter (3) 

; Processed:  Req #1518 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  25-Jul-92 00:00:00
; Actual run: 25-Jul-92 03:33:35
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Enter (3)  at  25-Jul-92 03:33:40
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Sat, 15 Aug 92 0:00:17 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: SPSUB
Last logout: 16 Jul 92


----------
RCPT To: <SPSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Thu, 16 Jul 92 17:01:02 UT 
To: SPSUB 
Subject: Req #1170 DSK:(SPSUB)SOFTVN.CMD Abort-Time (12) 

; Processed:  Req #1170 DSK:(SPSUB)SOFTVN.DOC=DSK:(SPSUB)SOFTVN.CMD
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 16-Jul-92 12:00:32
;
; Options:  Log:Supersede Mail:Error Restart:Repeat Unique:Job
; Limits:  Time 300  TRUs 0
; Flags: 
; Status:  Abort-Time (12)  at  16-Jul-92 17:01:00
;
; Output recorded in file DSK:(SPSUB)SOFTVN.DOC.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Tue, 1 Sep 92 0:00:06 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 31 Aug 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sun, 2 Aug 92 13:45:25 UT 
To: ENSS 
Subject: Req #518 DSK:(ENSS)BACKUP.MON Abort-License (0) 

; Processed:  Req #518 DSK:(ENSS)BACKUP.MON
; Scheduled:  02-Aug-92 08:00:00
; Actual run: 07-Jun-92 08:52:41
;
; Options:  Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-License (0)  at  02-Aug-92 09:45:23

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Tue, 1 Sep 92 0:00:06 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 31 Aug 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 8 Aug 92 6:26:44 UT 
To: ENSS 
Subject: Req #1837 DSK:(ENSS)ONTSLV.SUB Abort-Notice (5) 

; Processed:  Req #1837 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  08-Aug-92 00:00:00
; Actual run: 08-Aug-92 00:00:02
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (5)  at  08-Aug-92 02:26:43
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 12 Nov 92 0:00:32 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 11 Nov 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Tue, 13 Oct 92 5:52:00 UT 
To: ENSS 
Subject: Req #3231 DSK:(ENSS)ONTSLV.SUB Abort-Notice (5) 

; Processed:  Req #3231 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  13-Oct-92 00:00:00
; Actual run: 13-Oct-92 00:00:06
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (5)  at  13-Oct-92 01:52:00
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Thu, 12 Nov 92 0:00:33 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 11 Nov 92


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Fri, 30 Oct 92 23:10:44 UT 
To: ENSS 
Subject: Req #3477 DSK:(ENSS)PROOF.SUB Abort-Zap (1) 

; Processed:  Req #3477 DSK:(ENSS)PROOF.OUT=DSK:(ENSS)PROOF.SUB
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 30-Oct-92 18:09:39
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Zap (1)  at  30-Oct-92 18:10:38
;
; Output recorded in file DSK:(ENSS)PROOF.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Sun, 29 Nov 92 0:00:03 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: BTSUB
Last logout: 26 Nov 92


----------
RCPT To: <BTSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Fri, 30 Oct 92 23:10:36 UT 
To: BTSUB 
Subject: Req #3371 DSK:(BTSUB)SOFTVN.CMD Abort-Enter (3) 

; Processed:  Req #3371 DSK:(BTSUB)SOFTVN.DOC=DSK:(BTSUB)SOFTVN.CMD
; Scheduled:  29-Oct-92 16:00:00
; Actual run: 30-Oct-92 23:10:19
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 120  TRUs 0
; Flags: 
; Status:  Abort-Enter (3)  at  30-Oct-92 23:10:31
;
; Output recorded in file DSK:(BTSUB)SOFTVN.DOC.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 30 Nov 92 0:00:04 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: EDUSUB
Last logout: 29 Nov 92


----------
RCPT To: <EDUSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 31 Oct 92 17:17:11 UT 
To: EDUSUB 
Subject: Req #3487 DSK:(EDUSUB)AFDCLN.SUB Abort-Time (0) 

; Processed:  Req #3487 DSK:(EDUSUB)AFDCLN.TMP=DSK:(EDUSUB)AFDCLN.SUB
; Scheduled:  31-Oct-92 07:00:00
; Actual run: 31-Oct-92 15:36:18
;
; Options:  Log:Supersede Mail:Error Restart:Repeat Unique:Job
; Limits:  Time 100  TRUs 0
; Flags: 
; Status:  Abort-Time (0)  at  31-Oct-92 17:17:10
;
; Output recorded in file DSK:(EDUSUB)AFDCLN.TMP.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 30 Nov 92 0:00:04 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: EDUSUB
Last logout: 29 Nov 92


----------
RCPT To: <EDUSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 31 Oct 92 19:00:12 UT 
To: EDUSUB 
Subject: Req #3487 DSK:(EDUSUB)AFDCLN.SUB Abort-Time (0) 

; Processed:  Req #3487 DSK:(EDUSUB)AFDCLN.TMP=DSK:(EDUSUB)AFDCLN.SUB
; Scheduled:  31-Oct-92 07:00:00
; Actual run: 31-Oct-92 15:36:18
;
; Options:  Log:Supersede Mail:Error Restart:Repeat Unique:Job
; Limits:  Time 100  TRUs 0
; Flags: 
; Status:  Abort-Time (0)  at  31-Oct-92 19:00:10
;
; Output recorded in file DSK:(EDUSUB)AFDCLN.TMP.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 30 Nov 92 0:00:05 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: EDUSUB
Last logout: 29 Nov 92


----------
RCPT To: <EDUSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Tue, 3 Nov 92 7:00:15 UT 
To: EDUSUB 
Subject: Req #3517 DSK:(EDUSUB)AFDCLN.SUB Abort-Notice (1) 

; Processed:  Req #3517 DSK:(EDUSUB)AFDCLN.TMP=DSK:(EDUSUB)AFDCLN.SUB
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 03-Nov-92 07:00:12
;
; Options:  Log:Supersede Mail:Error Restart:Repeat Unique:Job
; Limits:  Time 100  TRUs 0
; Flags: 
; Status:  Abort-Notice (1)  at  03-Nov-92 07:00:14
;
; Output recorded in file DSK:(EDUSUB)AFDCLN.TMP.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 30 Nov 92 0:00:05 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: UKLAB
Last logout: 28 Nov 92


----------
RCPT To: <UKLAB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 31 Oct 92 17:17:12 UT 
To: UKLAB 
Subject: Req #3401 DSK:(UKLAB)AFDCLN.SUB Abort-Time (0) 

; Processed:  Req #3401 DSK:(UKLAB)AFDCLN.DOC=DSK:(UKLAB)AFDCLN.SUB
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 31-Oct-92 15:36:36
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 100  TRUs 0
; Flags: 
; Status:  Abort-Time (0)  at  31-Oct-92 17:17:11
;
; Output recorded in file DSK:(UKLAB)AFDCLN.DOC.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 30 Nov 92 0:00:05 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: UKLAB
Last logout: 28 Nov 92


----------
RCPT To: <UKLAB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 31 Oct 92 19:00:17 UT 
To: UKLAB 
Subject: Req #3401 DSK:(UKLAB)AFDCLN.SUB Abort-Time (0) 

; Processed:  Req #3401 DSK:(UKLAB)AFDCLN.DOC=DSK:(UKLAB)AFDCLN.SUB
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 31-Oct-92 15:36:36
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 100  TRUs 0
; Flags: 
; Status:  Abort-Time (0)  at  31-Oct-92 19:00:16
;
; Output recorded in file DSK:(UKLAB)AFDCLN.DOC.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Tue, 1 Dec 92 0:00:31 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: MISSUB
Last logout: 25 Nov 92


----------
RCPT To: <MISSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sun, 1 Nov 92 12:35:11 UT 
To: MISSUB 
Subject: Req #3486 DSK:(MISSUB)AFDBAK.SUB Abort-Notice (0) 

; Processed:  Req #3486 DSK:(MISSUB)AFDBAK.DOC=DSK:(MISSUB)AFDBAK.SUB
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 31-Oct-92 15:36:12
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 300  TRUs 0
; Flags: 
; Status:  Abort-Notice (0)  at  01-Nov-92 12:35:08
;
; Output recorded in file DSK:(MISSUB)AFDBAK.DOC.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Tue, 1 Dec 92 0:00:33 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: MISSUB
Last logout: 25 Nov 92


----------
RCPT To: <MISSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Tue, 3 Nov 92 7:00:14 UT 
To: MISSUB 
Subject: Req #3516 DSK:(MISSUB)AFDBAK.SUB Abort-Notice (2) 

; Processed:  Req #3516 DSK:(MISSUB)AFDBAK.DOC=DSK:(MISSUB)AFDBAK.SUB
; Scheduled:  03-Nov-92 07:00:00
; Actual run: 03-Nov-92 07:00:00
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 300  TRUs 0
; Flags: 
; Status:  Abort-Notice (2)  at  03-Nov-92 07:00:12
;
; Output recorded in file DSK:(MISSUB)AFDBAK.DOC.

RCPT To: <!PERPOPER/XEXECX.MSG>
Received: from F74.Tymnet.COM by F26.Tymnet.COM; Thu, 31 Dec 92 16:02:06 PST
Return-path: <Postmaster@F74.Tymnet.COM> 
From: Postmaster@F74.Tymnet.COM 
Date: Fri, 1 Jan 93 0:00:44 UT 
To: <PERPOPER@F26.Tymnet.COM> 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: JMS
Last logout: 31 Dec 92


----------
RCPT To: <!JMS@F74.Tymnet.COM> 
Received: from F26.Tymnet.COM by F74.Tymnet.COM; Thu, 17 Dec 92 8:30:47 PST
Return-path: <PERPOPER@F26.Tymnet.COM> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Thu, 17 Dec 92 16:30:36 UT 
To: JMS 
Subject: Req #4140 DSK:(JMS)FNDBAD.CTL Abort-Time (0) 

; Processed:  Req #4140 DSK:(JMS)FNDBAD.LOG=DSK:(JMS)FNDBAD.CTL
; Scheduled:  17-Dec-92 07:30:00
; Actual run: 17-Dec-92 07:30:04
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-Time (0)  at  17-Dec-92 08:30:36
;
; Output recorded in file DSK:(JMS)FNDBAD.LOG.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Tue, 5 Jan 93 0:00:28 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 4 Jan 93


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sun, 6 Dec 92 13:20:21 UT 
To: ENSS 
Subject: Req #3905 DSK:(ENSS)ONTSLV.SUB Abort-Notice (0) 

; Processed:  Req #3905 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  29-Nov-92 00:00:00
; Actual run: 29-Nov-92 00:00:04
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (0)  at  06-Dec-92 08:20:21
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Sun, 7 Feb 93 0:00:16 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 6 Feb 93


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Fri, 8 Jan 93 19:57:42 UT 
To: ENSS 
Subject: Req #4466 DSK:(ENSS)APPEND. Abort-Zap (3) 

; Processed:  Req #4466 DSK:(ENSS)APPEND.LOG=DSK:(ENSS)APPEND.
; Scheduled:  08-Jan-93 14:54:35
; Actual run: 08-Jan-93 14:56:27
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-Zap (3)  at  08-Jan-93 14:57:35
;
; Output recorded in file DSK:(ENSS)APPEND.LOG.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Sun, 7 Feb 93 0:00:18 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 6 Feb 93


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Fri, 8 Jan 93 20:00:04 UT 
To: ENSS 
Subject: Req #4466 DSK:(ENSS)APPEND. Abort-Zap (3) 

; Processed:  Req #4466 DSK:(ENSS)APPEND.LOG=DSK:(ENSS)APPEND.
; Scheduled:  08-Jan-93 14:58:39
; Actual run: 08-Jan-93 14:58:44
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-Zap (3)  at  08-Jan-93 15:00:02
;
; Output recorded in file DSK:(ENSS)APPEND.LOG.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Tue, 16 Mar 93 0:00:13 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 15 Mar 93


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sun, 14 Feb 93 11:55:42 UT 
To: ENSS 
Subject: Req #4937 DSK:(ENSS)ONTSLV.SUB Abort-Notice (0) 

; Processed:  Req #4937 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  11-Feb-93 12:00:00
; Actual run: 11-Feb-93 12:00:06
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (0)  at  14-Feb-93 06:55:42
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Tue, 16 Mar 93 0:00:13 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 15 Mar 93


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Thu, 18 Feb 93 19:18:09 UT 
To: ENSS 
Subject: Req #4466 DSK:(ENSS)APPEND. Abort-Zap (3) 

; Processed:  Req #4466 DSK:(ENSS)APPEND.LOG=DSK:(ENSS)APPEND.
; Scheduled:  18-Feb-93 14:16:59
; Actual run: 18-Feb-93 14:17:08
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-Zap (3)  at  18-Feb-93 14:18:06
;
; Output recorded in file DSK:(ENSS)APPEND.LOG.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Tue, 16 Mar 93 0:00:14 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 15 Mar 93


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sun, 14 Mar 93 12:53:16 UT 
To: ENSS 
Subject: Req #5233 DSK:(ENSS)ONTSLV.SUB Abort-Notice (0) 

; Processed:  Req #5233 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  09-Mar-93 12:00:00
; Actual run: 09-Mar-93 12:00:05
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (0)  at  14-Mar-93 07:53:15
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Tue, 16 Mar 93 0:00:14 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 15 Mar 93


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Mon, 15 Mar 93 15:26:12 UT 
To: ENSS 
Subject: Req #4466 DSK:(ENSS)APPEND. Abort-Zap (3) 

; Processed:  Req #4466 DSK:(ENSS)APPEND.LOG=DSK:(ENSS)APPEND.
; Scheduled:  15-Mar-93 10:24:31
; Actual run: 15-Mar-93 10:24:42
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-Zap (3)  at  15-Mar-93 10:26:08
;
; Output recorded in file DSK:(ENSS)APPEND.LOG.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Wed, 31 Mar 93 0:00:40 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: GONET
Last logout: 1 Mar 93


----------
RCPT To: <GONET> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Mon, 1 Mar 93 15:20:26 UT 
To: GONET 
Subject: Req #5046 DSK:(GONET)AFDBAK.SUB Abort-Time (4) 

; Processed:  Req #5046 DSK:(GONET)AFDBAK.DOC=DSK:(GONET)AFDBAK.SUB
; Scheduled:  01-Mar-93 12:00:00
; Actual run: 01-Mar-93 12:00:01
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 200  TRUs 0
; Flags: 
; Status:  Abort-Time (4)  at  01-Mar-93 15:20:24
;
; Output recorded in file DSK:(GONET)AFDBAK.DOC.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 5 Apr 93 0:00:12 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: EDUSUB
Last logout: 4 Mar 93


----------
RCPT To: <EDUSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 6 Mar 93 0:01:10 UT 
To: EDUSUB 
Subject: Req #5177 DSK:(EDUSUB)AFDBAK.SUB Abort-Time (0) 

; Processed:  Req #5177 DSK:(EDUSUB)AFDBAK.DOC=DSK:(EDUSUB)AFDBAK.SUB
; Scheduled:  05-Mar-93 19:00:00
; Actual run: 05-Mar-93 19:00:05
;
; Options:  Log:Supersede Mail:Error Restart:Repeat Unique:Job
; Limits:  Time 300  TRUs 0
; Flags: 
; Status:  Abort-Time (0)  at  06-Mar-93 00:01:07
;
; Output recorded in file DSK:(EDUSUB)AFDBAK.DOC.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 31 May 93 0:00:11 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 30 May 93


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sat, 1 May 93 7:12:17 UT 
To: ENSS 
Subject: Req #5807 DSK:(ENSS)ONTSLV.SUB Abort-Notice (0) 

; Processed:  Req #5807 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  29-Apr-93 12:00:00
; Actual run: 29-Apr-93 12:00:06
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (0)  at  01-May-93 03:12:16
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 31 May 93 0:00:12 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 30 May 93


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Fri, 7 May 93 14:05:32 UT 
To: ENSS 
Subject: Req #4466 DSK:(ENSS)APPEND. Abort-Zap (3) 

; Processed:  Req #4466 DSK:(ENSS)APPEND.LOG=DSK:(ENSS)APPEND.
; Scheduled:  07-May-93 10:02:56
; Actual run: 07-May-93 10:03:00
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-Zap (3)  at  07-May-93 10:05:31
;
; Output recorded in file DSK:(ENSS)APPEND.LOG.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 31 May 93 0:00:13 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 30 May 93


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sun, 9 May 93 14:12:08 UT 
To: ENSS 
Subject: Req #5850 DSK:(ENSS)ONTSLV.SUB Abort-Notice (0) 

; Processed:  Req #5850 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  05-May-93 12:00:00
; Actual run: 05-May-93 12:00:11
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (0)  at  09-May-93 10:12:07
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
Received: from F38.Tymnet.COM by F26.Tymnet.COM; Mon, 5 Jul 93 17:00:06 PDT
Return-path: <Postmaster@F38.Tymnet.COM> 
From: Postmaster@F38.Tymnet.COM 
Date: Tue, 6 Jul 93 0:00:02 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: 21477263665
Last logout: 1 Jan 64


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sun, 6 Jun 93 11:13:10 UT 
To: ENSS 
Subject: Req #6088 DSK:(ENSS)ONTSLV.SUB Abort-Notice (0) 

; Processed:  Req #6088 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  02-Jun-93 12:00:00
; Actual run: 02-Jun-93 12:00:04
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (0)  at  06-Jun-93 07:13:09
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
Received: from F34.Tymnet.COM by F26.Tymnet.COM; Mon, 5 Jul 93 17:00:06 PDT
Return-path: <Postmaster@F34.Tymnet.COM> 
From: Postmaster@F34.Tymnet.COM 
Date: Tue, 6 Jul 93 0:00:02 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: 21477263665
Last logout: 1 Jan 64


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sun, 6 Jun 93 11:13:10 UT 
To: ENSS 
Subject: Req #6088 DSK:(ENSS)ONTSLV.SUB Abort-Notice (0) 

; Processed:  Req #6088 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  02-Jun-93 12:00:00
; Actual run: 02-Jun-93 12:00:04
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (0)  at  06-Jun-93 07:13:09
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 5 Jul 93 17:00:12 PDT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 5 Jul 93


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sun, 6 Jun 93 11:13:10 UT 
To: ENSS 
Subject: Req #6088 DSK:(ENSS)ONTSLV.SUB Abort-Notice (0) 

; Processed:  Req #6088 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  02-Jun-93 12:00:00
; Actual run: 02-Jun-93 12:00:04
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (0)  at  06-Jun-93 07:13:09
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Mon, 5 Jul 93 17:00:13 PDT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 5 Jul 93


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Tue, 29 Jun 93 20:32:54 UT 
To: ENSS 
Subject: Req #4466 DSK:(ENSS)APPEND. Abort-Zap (3) 

; Processed:  Req #4466 DSK:(ENSS)APPEND.LOG=DSK:(ENSS)APPEND.
; Scheduled:  29-Jun-93 16:29:19
; Actual run: 29-Jun-93 16:29:25
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Abort-Zap (3)  at  29-Jun-93 16:32:52
;
; Output recorded in file DSK:(ENSS)APPEND.LOG.

RCPT To: <!PERPOPER/XEXECX.MSG>
Received: from F38.Tymnet.COM by F26.Tymnet.COM; Fri, 16 Jul 93 17:00:13 PDT
Return-path: <Postmaster@F38.Tymnet.COM> 
From: Postmaster@F38.Tymnet.COM 
Date: Sat, 17 Jul 93 0:00:03 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: 47256731317
Last logout: 1 Jan 64


----------
RCPT To: <BTSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Thu, 17 Jun 93 17:05:47 UT 
To: BTSUB 
Subject: Req #6129 DSK:(BTSUB)SOFTVN.CMD Abort-Time (0) 

; Processed:  Req #6129 DSK:(BTSUB)SOFTVN.DOC=DSK:(BTSUB)SOFTVN.CMD
; Scheduled:  17-Jun-93 16:00:00
; Actual run: 17-Jun-93 16:00:06
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 120  TRUs 0
; Flags: 
; Status:  Abort-Time (0)  at  17-Jun-93 18:05:46
;
; Output recorded in file DSK:(BTSUB)SOFTVN.DOC.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Sat, 17 Jul 93 0:00:16 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: BTSUB
Last logout: 10 Jun 93


----------
RCPT To: <BTSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Thu, 17 Jun 93 17:05:47 UT 
To: BTSUB 
Subject: Req #6129 DSK:(BTSUB)SOFTVN.CMD Abort-Time (0) 

; Processed:  Req #6129 DSK:(BTSUB)SOFTVN.DOC=DSK:(BTSUB)SOFTVN.CMD
; Scheduled:  17-Jun-93 16:00:00
; Actual run: 17-Jun-93 16:00:06
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 120  TRUs 0
; Flags: 
; Status:  Abort-Time (0)  at  17-Jun-93 18:05:46
;
; Output recorded in file DSK:(BTSUB)SOFTVN.DOC.

RCPT To: <!PERPOPER/XEXECX.MSG>
Received: from F34.Tymnet.COM by F26.Tymnet.COM; Fri, 16 Jul 93 17:02:50 PDT
Return-path: <Postmaster@F34.Tymnet.COM> 
From: Postmaster@F34.Tymnet.COM 
Date: Sat, 17 Jul 93 0:01:28 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: 47256731317
Last logout: 1 Jan 64


----------
RCPT To: <BTSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Thu, 17 Jun 93 17:05:47 UT 
To: BTSUB 
Subject: Req #6129 DSK:(BTSUB)SOFTVN.CMD Abort-Time (0) 

; Processed:  Req #6129 DSK:(BTSUB)SOFTVN.DOC=DSK:(BTSUB)SOFTVN.CMD
; Scheduled:  17-Jun-93 16:00:00
; Actual run: 17-Jun-93 16:00:06
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 120  TRUs 0
; Flags: 
; Status:  Abort-Time (0)  at  17-Jun-93 18:05:46
;
; Output recorded in file DSK:(BTSUB)SOFTVN.DOC.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Tue, 7 Sep 93 0:00:09 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: ENSS
Last logout: 11 Aug 93


----------
RCPT To: <ENSS> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Sun, 8 Aug 93 10:58:30 UT 
To: ENSS 
Subject: Req #6695 DSK:(ENSS)ONTSLV.SUB Abort-Notice (0) 

; Processed:  Req #6695 DSK:(ENSS)ONTSLV.OUT=DSK:(ENSS)ONTSLV.SUB
; Scheduled:  03-Aug-93 12:00:00
; Actual run: 03-Aug-93 12:00:02
;
; Options:  Log:Supersede Mail:Error Restart:Start Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (0)  at  08-Aug-93 06:58:29
;
; Output recorded in file DSK:(ENSS)ONTSLV.OUT.

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@F26.Tymnet.COM 
Date: Fri, 10 Sep 93 0:00:16 UT 
To: PERPOPER@F26.Tymnet.COM 
Subject: Returned MAIL 

The following message was not delivered because:
User has not read mail in 30 days: MISSUB
Last logout: 4 Aug 93


----------
RCPT To: <MISSUB> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet.COM 
Date: Wed, 11 Aug 93 18:46:18 UT 
To: MISSUB 
Subject: Req #6701 DSK:(MISSUB)AFDCLN.SUB Abort-Time (0) 

; Processed:  Req #6701 DSK:(MISSUB)AFDCLN.DOC=DSK:(MISSUB)AFDCLN.SUB
; Scheduled:  11-Aug-93 18:00:00
; Actual run: 11-Aug-93 18:00:03
;
; Options:  Log:Supersede Mail:Error Unique:Job
; Limits:  Time 45  TRUs 0
; Flags: 
; Status:  Abort-Time (0)  at  11-Aug-93 18:46:16
;
; Output recorded in file DSK:(MISSUB)AFDCLN.DOC.

    7tn)