;@(MOORING)SLCOP.TYM
;@(ISIS2)START.LIB
;@(ISIS2)FRING.LIB
;@(ISIS2)CRASH.LIB
;@(MOORING)SLCOP.NAD
;@(ISIS2)FINISH.LIB
1;FSLCOP.NIB
CTA,CTASIZ;PSEG0,S0SIZE;PSEG1,S1SIZE;PSEG2,S2SIZE;PSEG8,S8SIZE;PSEG9,S9SIZE;PSEGA,SASIZE;P%P%Q
