;; SAMPLE COMMAND FILE - T-II NODE CODE - VERSION 05.22
;; REVISED   7-9-87  cwc
;; >>SOLO SWITCHER<<
;;
;A(SOURCE)TII05.I22
;AND____.TYM
;ASOXRAY.GGY
;A(SOURCE)TII05.R22
;A(SOURCE)TII05.F22
;; ASSEMBLE PATCHES IF ANY
;A(SOURCE)TII05.P22
1;FND____.BND
70;TPRIVBG,RANGE1;PSEG1BG,SEG1RL,SEG1SZ;PXRAYBG,XRAYRL,XRAYSZ;P%P%Q

