**************************************************************************

          THIS DIRECTORY IS TO BE USED FOR STORAGE OF FILES
          RELATED TO THE DEVELOPMENT AND MAINTENANCE OF THE
          PAPER PROGRAM.  ANY UNAUTHORIZED FILES THAT ARE
          CAUGHT LOITERING AROUND HERE WILL BE SUMMARILY
          EXECUTED.  CALL JIM PARKER OR STEVE PALMER BEFORE
          DOING ANYTHING TO OR WITH FILES THAT ARE STORED IN
          THIS DIRECTORY.
          JIM PARKER- 610/666-3460, VNET 889-3460
          STEVE PALMER- 610/666-3401 OR 800/937-2862 X893

**************************************************************************
