	LO	UTSPTP

:  THE FOLLOWING MUST BE DONE BECAUSE WE GOT AN ASSEMBLY ERROR - OUT RANGE
	PATCH(880719,1320,MJASTRZ,PENTER+8,,6)
	J	PA1PTR,,
	CONPATCH(PA1PTR,,0C)
	LHL	R5,RSEG,R1,R3
	J	RSEG,R5,,
	ENDPATCH(FIX ASSEMBLY ERROR AROUND <PENTER>)

