::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::   TYMCOM MESSAGE TABLE FOR 8BIT HOST
::   (NSCNET)TYMCOM.MSG
::   02 MAY,1986 BY Y.FURUTA
::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:                A  L  L     P  O  R  T  S     D  O  W  N
MTEXT(APD,"0D"0A"41"4C"4C"20"50"4F"52"54"53"20"44"4F"57"4E)

:                N  O     P  O  R  T  S     A  V  A  I  L  A  B  L  E
MTEXT(NPA,"0D"0A"4E"4F"20"50"4F"52"54"53"20"41"56"41"49"4C"41"42"4C"45)

:                R  I  N  G     N  O     A  N  S  W  E  R
MTEXT(RNA,"0D"0A"52"49"4E"47"20"4E"4F"20"41"4E"53"57"45"52)

MTEXT(PN)

:                 i  s     O  n  L  i  n  e     [     W  e  l  c  o  m  e     t  o     K  y  o  w  a  -  N  E  T     ]
MTEXT(GRT,"0D"0AXXXX"20"69"73"20"4F"6E"4C"69"6E"65"0D"0A"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"20"5B"20"57"65"6C"63"6F"6D"65"20"74"6F"20"4E"61"67"6F"79"61"20"4B"79"6F"77"61"2D"4E"45"54"20"5D"20"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"2D"3A"0D"0A"0D"0A,3)

:                U  S  E  R  N  A  M  E     I  N  V  A  L  I  D
MTEXT(IUN,"0D"0A"55"53"45"52"4E"41"4D"45"20"49"4E"56"41"4C"49"44)

:                A  C  C  E  S  S     N  O  T     P  E  R  M  I  T  T  E  D
MTEXT(ANP,"0D"0A"41"43"43"45"53"53"20"4E"4F"54"20"50"45"52"4D"49"54"54"45"44)

:                D  R  O  P  P  E  D     F  O  R     I  N  A  C  T  I  V  I  T  Y
MTEXT(INA,"0D"0A"44"52"4F"50"50"45"44"20"46"4F"52"20"49"4E"41"43"54"49"56"49"54"59)

:                D  R  O  P  P  E  D     B  Y     H  O  S  T
MTEXT(DBH,"0D"0A"44"52"4F"50"50"45"44"20"42"59"20"48"4F"53"54)

:          H  O  S  T     D  I  D  N  T     A  C  K     U  S  E  R     D  I  S  C
MTEXT(NHA,"48"4F"53"54"20"44"49"44"4E"54"20"41"43"4B"20"55"53"45"52"20"44"49"53"43"0D"0A)

:                       I  S     D  O  W  N
MTEXT(HDN,"0D"0AXXXX"20"69"73"20"44"4F"57"4E,3)

:                       I  S     S  H  U  T
MTEXT(HSH,"0D"0AXXXX"20"69"73"20"53"48"55"54,3)

:                 D  I  S  C  O  N  N  E  C  T  I  N  G
MTEXT(LOFF,"0D"0A"44"49"53"43"4F"4E"4E"45"43"54"49"4E"47)

:                 D  A  T  A     L  O  S  T     T  O     H  O  S  T
MTEXT(BZFT,"07"07"44"41"54"41"20"4C"4F"53"54"20"54"4F"20"48"4F"53"54)

:                 D  A  T  A     L  O  S  T     T  O     T  E  R  M  I  N  A  L
MTEXT(BZTT,"07"07"44"41"54"41"20"4C"4F"53"54"20"54"4F"20"54"45"52"4D"49"4E"41"4C)
