From: UKSUP@F26.Tymnet.COM 
Date: Thu, 3 Aug 89 12:48:27 UT 
To: UKSUP 
Subject: "PCOM v1.63 processed: Options:"... 

; PCOM v1.63 - processed: (UKLAB)LB2001.OUT = (UKLAB)LB2001.PCM
; Options: DETACH  LOG NOAPPEND SUPERSEDE LICENSE 
; Limits: TIME:60 TRULIMIT:0 
; Status: completed.
; Output recorded in file (UKLAB)LB2001.OUT.
From: UKSUP@F26.Tymnet.COM 
Date: Wed, 30 Aug 89 14:32:28 UT 
To: UKSUP 
Subject: "PCOM v1.63 processed: Options:"... 

; PCOM v1.63 - processed: (UKLAB)LB2502.OUT = (UKLAB)LB2502.PCO
; Options: DETACH  LOG NOAPPEND SUPERSEDE LICENSE 
; Limits: TIME:60 TRULIMIT:0 
; Status: completed.
; Output recorded in file (UKLAB)LB2502.OUT.
From: UKSUP@F26.Tymnet.COM 
Date: Wed, 13 Sep 89 10:06:55 UT 
To: UKSUP 
Subject: "PCOM v1.63 processed: Options:"... 

; PCOM v1.63 - processed: (UKLAB)LB2012.OUT = (UKLAB)LB2012.PCO
; Options: DETACH  LOG NOAPPEND SUPERSEDE LICENSE 
; Limits: TIME:60 TRULIMIT:0 
; Status: completed.
; Output recorded in file (UKLAB)LB2012.OUT.
From: UKSUP@F26.Tymnet.COM 
Date: Mon, 2 Oct 89 15:12:12 UT 
To: UKSUP 
Subject: "PCOM v1.63 processed: Options:"... 

; PCOM v1.63 - processed: (UKSUP)SLSDN4.DOC = (UKSUP)SLSDN4.PCO
; Options: DETACH  LOG NOAPPEND SUPERSEDE LICENSE 
; Limits: TIME:60 TRULIMIT:0 
; Status: completed.
; Output recorded in file (UKSUP)SLSDN4.DOC.
From: UKSUP@F26.Tymnet.COM 
Date: Mon, 6 Nov 89 15:07:58 UT 
To: UKSUP 
Subject: "PCOM v1.63 processed: Options:"... 

; PCOM v1.63 - processed: (UKLAB)049PCO.LOG = (UKLAB)LB2002.C10
; Options: DETACH  LOG NOAPPEND SUPERSEDE LICENSE 
; Limits: TIME:60 TRULIMIT:0 
; Status: completed.
; Output recorded in file (UKLAB)049PCO.LOG.
From: UKSUP@F26.Tymnet.COM 
Date: Mon, 6 Nov 89 15:37:07 UT 
To: UKSUP 
Subject: "PCOM v1.63 processed: Options:"... 

; PCOM v1.63 - processed: (UKLAB)071PCO.LOG = (UKLAB)LB2002.C10
; Options: DETACH  LOG NOAPPEND SUPERSEDE LICENSE 
; Limits: TIME:60 TRULIMIT:0 
; Status: completed.
; Output recorded in file (UKLAB)071PCO.LOG.
From: UKSUP@F26.Tymnet.COM 
Date: Mon, 6 Nov 89 16:41:55 UT 
To: UKSUP 
Subject: "PCOM v1.63 processed: Options:"... 

; PCOM v1.63 - processed: (UKLAB)065PCO.LOG = (UKLAB)HM2002.C10
; Options: DETACH  LOG NOAPPEND SUPERSEDE LICENSE 
; Limits: TIME:60 TRULIMIT:0 
; Status: completed.
; Output recorded in file (UKLAB)065PCO.LOG.
From: UKSUP@F26.Tymnet.COM 
Date: Tue, 7 Nov 89 10:55:17 UT 
To: UKSUP 
Subject: "PCOM v1.63 processed: Options:"... 

; PCOM v1.63 - processed: (UKLAB)049PCO.LOG = (UKLAB)HM2002.C10
; Options: DETACH  LOG NOAPPEND SUPERSEDE LICENSE 
; Limits: TIME:60 TRULIMIT:0 
; Status: completed.
; Output recorded in file (UKLAB)049PCO.LOG.
