:GOOD GUY LIST FOR ACCESS TO DDT
:
XGG     MACRO [
        GG(L.DISC!L.S0A!L.SYA!L.SUA!L.S0P!L.SYP!L.P,-1,ISISTECH)
        GG(L.DISC!L.S0A!L.SYA!L.SUA!L.S0P!L.SYP!L.P,-1,HELLERDDT)
        GG(L.DISC!L.S0A!L.SYA!L.SUA!L.S0P!L.SYP!L.P,-1,DNSONLY)
        GG(L.S0A!L.SYA!L.S0R!L.SYR!L.R,-1,MAINTDIAG)
        GG(L.DISC!L.S0A!L.SYA!L.SUA!L.S0P!L.SYP!L.P,-1,JRINDE)
        GG(L.S0A!L.S0R!L.H!L.P,-1,GATEWAY)      :REQUIRED FOR LOADING!
        GG(L.S0A!L.S0R!L.H!L.P,-1,DLOAD)      :REQUIRED FOR LOADING!
        GG(L.SYA!L.SUA!L.S0A!L.DISC!L.SYP!L.S0P!L.P,-1,HORUS)
        IF      SUP
        GG(L.SUA!L.DISC!L.SYA!L.S0A!L.SYP!L.S0P!L.P,NSLOT+2,RPROBE)
GGPRO   GG(0,NSLOT+3002,PROBE)
GGERR   GG(0,NSLOT+3003,ERLOG)
GGACC   GG(0,NSLOT+3004,ACCOUNT)
GGSYS   GG(0,NSLOT+3005,SYSMSG1)
GGUN2   GG(0,NSLOT+3006,UN2)
        EI
]
        END
