R (UPL)X22
O BASE1
FI STAT CLSD SVER 1 HN 1 OR SVER 1 HN 4
SEARCH ELM GT 300
SORT ELM
REPORT START
HEADING PRI SYSDATE FORMAT 85X D3 // 5X 'DAILY REPORT OF SEV. 1 TICKETS&
WITH ELAPSED TIMES OVER 5 HOURS' 80X END
ON CHANGE STAT PRI FORMAT 'TICKET #       E.T. IN HOURS' 80X END
PRI TNUM (ELM/60) FORMAT I6 10X F END
REPORT END
CLOSE
Q

