        LO      BSCPTP
PATCH(891207,1230,WARNERD,PA0PTR,,4+12*NBILIN)
ENQTIM  WS      NBILIN
ACKTIM  WS      NBILIN
DSRTIM  WS      NBILIN
TMP1    WS      1

CONPATCH(RINIT,,6)
        J       PA1PTR,,

CONPATCH(PA1PTR,,1E)
        L       R0,FASTC,,
        ST      R0,ENQTIM,R9,R9
        TBT     RL,BSCSIN,,
        JN      IRESET,,
        J       RINIT+8,,
ENDPATCH(SAVE FASTC AFTER RECEIVING 'ENQ' FROM LOCAL DEVICE)
